### ISSUE TITLE
Issue reading this mods manual.

### ISSUE THREAD

**Issue by CMCarlsen** [DoctorFTB/summoningstructures#1]
Hey there, ran into an issue with the mod!
While trying to read the mods manual, the mod crashed my client. Server seems fine.

MC Version: 1.10.2
Forge Version: forge-12.18.3.2185

Method to reproduce:
Open the manual, and click either the "x" in the corner, or the "next" button in the bottom right. Client hangs for a moment and then crashes.

Crash Report:
http://pastebin.com/d1eDxW2x

I'm assuming the important part specific to this issue is here?:
http://pastebin.com/esA0AKxD

Thanks! Let me know if you need anything else!

**Comment by DoctorFTB** [comment]
Thanks to issue. This fix in 1.4 version mod for 1.10.2.
https://minecraft.curseforge.com/projects/summoningstructures/files
